
import com.mysql.jdbc.Blob;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.lang.System.Logger;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Main
 */
public class EditData extends javax.swing.JFrame {
int userid;
    /**
     * Creates new form EditData
     */
    public EditData() {
        
        initComponents();
        showVaccines();
         Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnOUTADMIN = new javax.swing.JButton();
        btnSAVE = new javax.swing.JButton();
        btnDELETE = new javax.swing.JButton();
        btnUPDATE = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        newNAME = new javax.swing.JTextField();
        newCONTACT = new javax.swing.JTextField();
        newADDRESS = new javax.swing.JTextField();
        newAGE = new javax.swing.JTextField();
        newDOSE = new javax.swing.JTextField();
        newGENDER = new javax.swing.JTextField();
        newDATE = new javax.swing.JTextField();
        newBRAND = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(47, 79, 79));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMIN DATA EDITING");

        btnOUTADMIN.setBackground(new java.awt.Color(47, 79, 79));
        btnOUTADMIN.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnOUTADMIN.setForeground(new java.awt.Color(255, 255, 255));
        btnOUTADMIN.setText("TO ADMIN");
        btnOUTADMIN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOUTADMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOUTADMINActionPerformed(evt);
            }
        });

        btnSAVE.setBackground(new java.awt.Color(47, 79, 79));
        btnSAVE.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnSAVE.setForeground(new java.awt.Color(255, 255, 255));
        btnSAVE.setText("EXIT");
        btnSAVE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAVEActionPerformed(evt);
            }
        });

        btnDELETE.setBackground(new java.awt.Color(47, 79, 79));
        btnDELETE.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnDELETE.setForeground(new java.awt.Color(255, 255, 255));
        btnDELETE.setText("DELETE");
        btnDELETE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEActionPerformed(evt);
            }
        });

        btnUPDATE.setBackground(new java.awt.Color(47, 79, 79));
        btnUPDATE.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnUPDATE.setForeground(new java.awt.Color(255, 255, 255));
        btnUPDATE.setText("UPDATE");
        btnUPDATE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "ADDRESS", "CONTACT", "AGE", "GENDER", "DOSE", "BRAND", "DATE"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(7);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(10);
        }

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Address");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contact");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Age");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dose");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Brand");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date");

        newNAME.setBackground(new java.awt.Color(47, 79, 79));
        newNAME.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        newNAME.setForeground(new java.awt.Color(255, 255, 255));
        newNAME.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newNAME.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        newNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newNAMEActionPerformed(evt);
            }
        });

        newCONTACT.setBackground(new java.awt.Color(47, 79, 79));
        newCONTACT.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        newCONTACT.setForeground(new java.awt.Color(255, 255, 255));
        newCONTACT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newCONTACT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        newCONTACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCONTACTActionPerformed(evt);
            }
        });

        newADDRESS.setBackground(new java.awt.Color(47, 79, 79));
        newADDRESS.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        newADDRESS.setForeground(new java.awt.Color(255, 255, 255));
        newADDRESS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newADDRESS.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        newADDRESS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newADDRESSActionPerformed(evt);
            }
        });

        newAGE.setBackground(new java.awt.Color(47, 79, 79));
        newAGE.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        newAGE.setForeground(new java.awt.Color(255, 255, 255));
        newAGE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newAGE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        newAGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAGEActionPerformed(evt);
            }
        });

        newDOSE.setBackground(new java.awt.Color(47, 79, 79));
        newDOSE.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        newDOSE.setForeground(new java.awt.Color(255, 255, 255));
        newDOSE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newDOSE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        newDOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDOSEActionPerformed(evt);
            }
        });

        newGENDER.setBackground(new java.awt.Color(47, 79, 79));
        newGENDER.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        newGENDER.setForeground(new java.awt.Color(255, 255, 255));
        newGENDER.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newGENDER.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        newGENDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGENDERActionPerformed(evt);
            }
        });

        newDATE.setBackground(new java.awt.Color(47, 79, 79));
        newDATE.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        newDATE.setForeground(new java.awt.Color(255, 255, 255));
        newDATE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newDATE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        newDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDATEActionPerformed(evt);
            }
        });

        newBRAND.setBackground(new java.awt.Color(47, 79, 79));
        newBRAND.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        newBRAND.setForeground(new java.awt.Color(255, 255, 255));
        newBRAND.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newBRAND.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        newBRAND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBRANDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnSAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnUPDATE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(825, 825, 825)
                                .addComponent(btnOUTADMIN, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(380, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(newCONTACT, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addComponent(newNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(newADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(newAGE, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(newGENDER, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(newBRAND, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(newDATE, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(newDOSE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newNAME)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newCONTACT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newAGE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newGENDER, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newDOSE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(8, 8, 8)
                        .addComponent(newBRAND, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnOUTADMIN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void showVaccines(){
    ArrayList<Vaccine> list = getVaccinesList();
    
    
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    Object [] row =  new Object[9];
    
    for (int i = 0; i < list.size(); i++) {
        
        row[0] = list.get(i).getFinalID();
        row[1] = list.get(i).getFinalNAME();
        row[2] = list.get(i).getFinalADDRESS();
        row[3] = list.get(i).getFinalCONTACT();
        row[4] = list.get(i).getFinalAGE();
        row[5] = list.get(i).getFinalGENDER();
        row[6] = list.get(i).getFinalDOSE();
        row[7] = list.get(i).getFinalBRAND();
        row[8] = list.get(i).getFinalDATE();
     //   row[9] = list.get(i).getFinalIMAGE();
        model.addRow(row);
      
    }
    
    
}



public ArrayList <Vaccine> getVaccinesList(){
     ArrayList<Vaccine> Vaccinelist = new   ArrayList<Vaccine>();
     String sqlquery = "SELECT * FROM finalinfo";
     
     PreparedStatement ps;
     ResultSet rs;
     
        try {
            ps = ConnectToDB.getConnection().prepareStatement(sqlquery);
             rs = ps.executeQuery(sqlquery);
        
        
        Vaccine vaccine;
        
         while (rs.next()) {
             vaccine = new Vaccine(rs.getInt("finalID")  , rs.getString("finalNAME")
                                                         , rs.getString("finalADDRESS")
                                                         , rs.getString("finalCONTACT")
                                                         , rs.getString("finalAGE")
                                                         , rs.getString("finalGENDER")
                                                         , rs.getString("finalDOSE")
                                                         , rs.getString("finalBRAND")
                                                         , rs.getString("finalDATE")
                                                       //  , (Blob) rs.getBlob("finalIMAGE")
             );
             Vaccinelist.add(vaccine);
         }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(EditData.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    return Vaccinelist;
}




    private void btnDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEActionPerformed
       
        PreparedStatement ps;
        ResultSet rs;
       
        
        //on progress
       
        try {
             String query = "DELETE FROM `finalinfo` WHERE finalID = ?";
            ps = ConnectToDB.getConnection().prepareStatement(query);
           
         
             ps.setString(1, String.valueOf(userid));
            if (ps.executeUpdate()!=0) {
                JOptionPane.showMessageDialog(null, "PROFILE DELETED SUCCESSFULLY");
                DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                showVaccines();
            }else{
            JOptionPane.showMessageDialog(null, "PROFILE DELETION FAILED");
            }
            
        } catch (SQLException ex) {
          
        }
        
        
        
    }//GEN-LAST:event_btnDELETEActionPerformed

    private void btnOUTADMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOUTADMINActionPerformed
        IntoAdmin Rr = new IntoAdmin();
                         Rr.setVisible(true);
                        this.setVisible(false);
    }//GEN-LAST:event_btnOUTADMINActionPerformed

    private void newNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newNAMEActionPerformed

    private void newCONTACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCONTACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newCONTACTActionPerformed

    private void newADDRESSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newADDRESSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newADDRESSActionPerformed

    private void newAGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAGEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newAGEActionPerformed

    private void newDOSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDOSEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newDOSEActionPerformed

    private void newGENDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGENDERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newGENDERActionPerformed

    private void newDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDATEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newDATEActionPerformed

    private void newBRANDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBRANDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newBRANDActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int j = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        newNAME.setText(model.getValueAt(j, 1).toString());
        newADDRESS.setText(model.getValueAt(j, 2).toString());
        newCONTACT.setText(model.getValueAt(j, 3).toString());
        newAGE.setText(model.getValueAt(j, 4).toString());
        newGENDER.setText(model.getValueAt(j, 5).toString());
        newDOSE.setText(model.getValueAt(j, 6).toString());
        newDATE.setText(model.getValueAt(j, 7).toString());
        newBRAND.setText(model.getValueAt(j, 8).toString());
        userid = Integer.parseInt(model.getValueAt(j, 0).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEActionPerformed
       PreparedStatement ps;
       ResultSet rs;
       
       String query =  "UPDATE finalinfo SET `finalNAME`=?,`finalADDRESS`=?,`finalCONTACT`=?,`finalAGE`=?,`finalGENDER`=?,`finalDOSE`=?,`finalBRAND`=?,`finalDATE`=? WHERE finalID=?";
       
        try {
            ps = ConnectToDB.getConnection().prepareStatement(query);
            
            ps.setString(1, newNAME.getText());
            ps.setString(2, newADDRESS.getText());
            ps.setString(3, newCONTACT.getText());
            ps.setString(4, newAGE.getText());
            ps.setString(5, newGENDER.getText());
            ps.setString(6, newDOSE.getText());
            ps.setString(7, newBRAND.getText());
            ps.setString(8, newDATE.getText());
            ps.setInt(9, userid);
            
            
            if (ps.executeUpdate()!=0) {
                JOptionPane.showMessageDialog(null, "UPDATED SUCCESSFULLY");
                DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                showVaccines();
            }else{
                JOptionPane.showMessageDialog(null, "UPDATE FAILED");
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(EditData.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
       
    }//GEN-LAST:event_btnUPDATEActionPerformed

    private void btnSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAVEActionPerformed
        RegisterPage Std = new RegisterPage();
        Std.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSAVEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDELETE;
    private javax.swing.JButton btnOUTADMIN;
    private javax.swing.JButton btnSAVE;
    private javax.swing.JButton btnUPDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField newADDRESS;
    private javax.swing.JTextField newAGE;
    private javax.swing.JTextField newBRAND;
    private javax.swing.JTextField newCONTACT;
    private javax.swing.JTextField newDATE;
    private javax.swing.JTextField newDOSE;
    private javax.swing.JTextField newGENDER;
    private javax.swing.JTextField newNAME;
    // End of variables declaration//GEN-END:variables
}
