
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Main
 */
public class IntoAdmin extends javax.swing.JFrame {

    /**
     * Creates new form IntoAdmin
     */
    public IntoAdmin() {
        initComponents();
         Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }
private String Vaccine;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */








    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chckbxSINOVAC = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        chckbxASTRAZENICA = new javax.swing.JCheckBox();
        chckbxPFIZER = new javax.swing.JCheckBox();
        chckbSINOPHARM = new javax.swing.JCheckBox();
        chckbxMODERNA = new javax.swing.JCheckBox();
        chckbxJOHNSON = new javax.swing.JCheckBox();
        chckbxGAMALEYA = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtLOC = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        vaccDate2 = new com.toedter.calendar.JDateChooser();
        vaccDate1 = new com.toedter.calendar.JDateChooser();
        vaccDate3 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        vaccDate5 = new com.toedter.calendar.JDateChooser();
        vaccDate4 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(47, 79, 79));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AVAILABLE VACCINE BRAND");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMINISTRATOR ACCESS");

        chckbxSINOVAC.setForeground(new java.awt.Color(255, 255, 255));
        chckbxSINOVAC.setText("SINOVAC");
        chckbxSINOVAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckbxSINOVACActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Please be careful of the data to be entered.");

        chckbxASTRAZENICA.setForeground(new java.awt.Color(255, 255, 255));
        chckbxASTRAZENICA.setText("ASTRAZENICA");
        chckbxASTRAZENICA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckbxASTRAZENICAActionPerformed(evt);
            }
        });

        chckbxPFIZER.setForeground(new java.awt.Color(255, 255, 255));
        chckbxPFIZER.setText("PFIZER");
        chckbxPFIZER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckbxPFIZERActionPerformed(evt);
            }
        });

        chckbSINOPHARM.setForeground(new java.awt.Color(255, 255, 255));
        chckbSINOPHARM.setText("SINOPHARM");
        chckbSINOPHARM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckbSINOPHARMActionPerformed(evt);
            }
        });

        chckbxMODERNA.setForeground(new java.awt.Color(255, 255, 255));
        chckbxMODERNA.setText("MODERNA");
        chckbxMODERNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckbxMODERNAActionPerformed(evt);
            }
        });

        chckbxJOHNSON.setForeground(new java.awt.Color(255, 255, 255));
        chckbxJOHNSON.setText("JOHNSON & JOHNSON");
        chckbxJOHNSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckbxJOHNSONActionPerformed(evt);
            }
        });

        chckbxGAMALEYA.setForeground(new java.awt.Color(255, 255, 255));
        chckbxGAMALEYA.setText("GAMALEYA");
        chckbxGAMALEYA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckbxGAMALEYAActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("VACCINE CENTER LOCATION");

        txtLOC.setForeground(new java.awt.Color(51, 51, 51));
        txtLOC.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtLOC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txtLOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLOCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chckbxASTRAZENICA)
                                .addComponent(chckbxPFIZER)
                                .addComponent(chckbxSINOVAC)
                                .addComponent(chckbxMODERNA)
                                .addComponent(chckbxJOHNSON)
                                .addComponent(chckbxGAMALEYA)
                                .addComponent(chckbSINOPHARM))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(txtLOC, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(chckbxSINOVAC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chckbxASTRAZENICA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chckbxPFIZER)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chckbxMODERNA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chckbxJOHNSON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chckbxGAMALEYA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chckbSINOPHARM)
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLOC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(250, 250, 210));

        vaccDate2.setBackground(new java.awt.Color(250, 250, 210));
        vaccDate2.setDateFormatString("y,MM,dd");

        vaccDate1.setBackground(new java.awt.Color(250, 250, 210));
        vaccDate1.setDateFormatString("y,MM,dd");

        vaccDate3.setBackground(new java.awt.Color(250, 250, 210));
        vaccDate3.setDateFormatString("y,MM,dd");

        jLabel4.setBackground(new java.awt.Color(47, 79, 79));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(47, 79, 79));
        jLabel4.setText("AVAILABLE DATES");

        vaccDate5.setBackground(new java.awt.Color(250, 250, 210));
        vaccDate5.setDateFormatString("y,MM,dd");

        vaccDate4.setBackground(new java.awt.Color(250, 250, 210));
        vaccDate4.setDateFormatString("y,MM,dd");

        jButton1.setBackground(new java.awt.Color(47, 79, 79));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SAVE");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(47, 79, 79));
        jButton2.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SIGN UP");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        DELETE.setBackground(new java.awt.Color(47, 79, 79));
        DELETE.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        DELETE.setForeground(new java.awt.Color(255, 255, 255));
        DELETE.setText("DATA TABLE");
        DELETE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETEMouseClicked(evt);
            }
        });
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(47, 79, 79));
        jButton3.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("EXIT");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(vaccDate4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vaccDate5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vaccDate3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vaccDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vaccDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DELETE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(vaccDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vaccDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vaccDate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vaccDate4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vaccDate5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(DELETE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chckbxSINOVACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbxSINOVACActionPerformed
     sinovac = "SINOVAC";
        
// TODO add your handling code here:
    }//GEN-LAST:event_chckbxSINOVACActionPerformed

    private void chckbxASTRAZENICAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbxASTRAZENICAActionPerformed
        astrazenica = "ASTRAZENICA";
    }//GEN-LAST:event_chckbxASTRAZENICAActionPerformed

    private void chckbxPFIZERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbxPFIZERActionPerformed
        pfizer = "PFIZER";
    }//GEN-LAST:event_chckbxPFIZERActionPerformed

    private void chckbSINOPHARMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbSINOPHARMActionPerformed
        sinopharm = "SINOPHARM";
    }//GEN-LAST:event_chckbSINOPHARMActionPerformed

    private void chckbxMODERNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbxMODERNAActionPerformed
        moderna = "MODERNA";
    }//GEN-LAST:event_chckbxMODERNAActionPerformed

    private void chckbxJOHNSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbxJOHNSONActionPerformed
        johnson = "JOHNSON";
    }//GEN-LAST:event_chckbxJOHNSONActionPerformed

    private void chckbxGAMALEYAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbxGAMALEYAActionPerformed
        gamaleya = "GAMALEYA";
    }//GEN-LAST:event_chckbxGAMALEYAActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
      /* JOptionPane.showMessageDialog(rootPane,"SAVED AND UPLOADED!!!");
       
        RegisterPage Rr = new RegisterPage();
        Rr.setVisible(true);
         this.setVisible(false);*/
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
          NewAdminAcc NaA = new NewAdminAcc();
        NaA.setVisible(true);
        this.setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
     
        /* vaccDate1 =?, vaccDate2=?, vaccDate3=?, vaccDate4= ?,vaccDate5=?*/
                    
         
               
        
                String insertquery = "REPLACE INTO updatevaccine SET vaccNum=1 ,SINOVAC = ?, ASTRAZENICA = ?, PFIZER = ?, MODERNA = ?, JOHNSON = ?, GAMALEYA = ?, SINOPHARM  = ?,vaccDate1 =?, vaccDate2=?, vaccDate3=?, vaccDate4= ?,vaccDate5=? ";
        try {
              PreparedStatement ps;
          ResultSet rs; 
              
             ps = ConnectToDB.getConnection().prepareStatement(insertquery);
            
            
            if (chckbxSINOVAC.isSelected()) {
                 ps.setString(1, sinovac);
            }else{
                 ps.setString(1, "SINOVAC X");
            }
            
            if (chckbxASTRAZENICA.isSelected()) {
                 ps.setString(2, astrazenica);
            }else{
                 ps.setString(2, "ASTRAZENICA X");
            }
            
            if (chckbxPFIZER.isSelected()) {
                 ps.setString(3, pfizer);
            }else{
                 ps.setString(3, "PFIZER X");
            }
            
            if (chckbxMODERNA.isSelected()) {
                 ps.setString(4, moderna);
            }else{
                 ps.setString(4, "MODERNA X");
            }
            
            if (chckbxJOHNSON.isSelected()) {
                ps.setString(5, johnson);
            }else{
                ps.setString(5, "JOHNSON X");
            }
            
            if (chckbxGAMALEYA.isSelected()) {
                ps.setString(6, gamaleya);
            }else{
                ps.setString(6, "GAMALEYA X");
            }
            
            if (chckbSINOPHARM.isSelected()) {
                ps.setString(7, sinopharm);
            }else{
                 ps.setString(7, "SINOPHARM X");
            }
   
           
         
            
                            ps.setString(8, ((JTextField)vaccDate1.getDateEditor().getUiComponent()).getText());
                             ps.setString(9, ((JTextField)vaccDate2.getDateEditor().getUiComponent()).getText());
                              ps.setString(10, ((JTextField)vaccDate3.getDateEditor().getUiComponent()).getText());
                               ps.setString(11, ((JTextField)vaccDate4.getDateEditor().getUiComponent()).getText());
                                ps.setString(12, ((JTextField)vaccDate5.getDateEditor().getUiComponent()).getText());
 
                 
                 if (ps.executeUpdate()!=0) {
                     JOptionPane.showMessageDialog(null, "VACCINES UPDATED");
                                     
                       RegisterPage rp = new RegisterPage();
                    rp.setVisible(true);
                    this.setVisible(false);
                     
                 }else{
                      JOptionPane.showMessageDialog(null, "VACCINE UPDATE FAILED");
                 }
                 
// TODO add your handling code here:
           
        } catch (SQLException ex) {
            Logger.getLogger(RegisterPage.class.getName()).log(Level.SEVERE, null, ex);
        }
                                      
              // TODO add your handling
        
        
             //////////////////
             
             
             
             
                String insertquery2 = "UPDATE `staticlocation` SET `centerVacc`=? WHERE centerID = 1";
        try {
              PreparedStatement ps;
              ResultSet rs; 
              
             ps = ConnectToDB.getConnection().prepareStatement(insertquery2);
            
                        ps.setString(1, txtLOC.getText());

          
                 
                 if (ps.executeUpdate()!=0) {
                     JOptionPane.showMessageDialog(null, "LOCATION UPDATED");
                                     
                      
                     
                 }else{
                      JOptionPane.showMessageDialog(null, "LOCATION UPDATE FAILED");
                 }
                 
// TODO add your handling code here:
           
        } catch (SQLException ex) {
           
        }
                                      
              
              
              
              
              
              
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DELETEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DELETEMouseClicked

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        EditData Rr = new EditData();
                         Rr.setVisible(true);
                        this.setVisible(false);
                        
    }//GEN-LAST:event_DELETEActionPerformed

    private void txtLOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLOCActionPerformed
      
    }//GEN-LAST:event_txtLOCActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         RegisterPage Std = new RegisterPage();
        Std.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private String sinovac;
     private String astrazenica;
      private String pfizer;
       private String moderna;
        private String johnson;
         private String gamaleya;
          private String sinopharm;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntoAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DELETE;
    private javax.swing.JCheckBox chckbSINOPHARM;
    private javax.swing.JCheckBox chckbxASTRAZENICA;
    private javax.swing.JCheckBox chckbxGAMALEYA;
    private javax.swing.JCheckBox chckbxJOHNSON;
    private javax.swing.JCheckBox chckbxMODERNA;
    private javax.swing.JCheckBox chckbxPFIZER;
    private javax.swing.JCheckBox chckbxSINOVAC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtLOC;
    private com.toedter.calendar.JDateChooser vaccDate1;
    private com.toedter.calendar.JDateChooser vaccDate2;
    private com.toedter.calendar.JDateChooser vaccDate3;
    private com.toedter.calendar.JDateChooser vaccDate4;
    private com.toedter.calendar.JDateChooser vaccDate5;
    // End of variables declaration//GEN-END:variables
}
