
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ItemListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Main
 */
public class IntoReg extends javax.swing.JFrame {

    /**
     * Creates new form IntoReg
     */
    public IntoReg() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
        
        
        
    }

   
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoRefresh = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbDate = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbDose = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbBrand = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnConfirmSched = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        infoREF = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        visibleCampaign = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        infoRefresh.setBackground(new java.awt.Color(47, 79, 79));
        infoRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infoRefreshMouseEntered(evt);
            }
        });
        infoRefresh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(47, 79, 79));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("If you already had a dose lately, Please bring your vaccine card for verification.");
        infoRefresh.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, -1, -1));

        jLabel2.setBackground(new java.awt.Color(47, 79, 79));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SCHEDULING");
        infoRefresh.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VACCINATION DATE");
        infoRefresh.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        cmbDate.setBackground(new java.awt.Color(47, 79, 79));
        cmbDate.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        cmbDate.setForeground(new java.awt.Color(255, 255, 255));
        cmbDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Refresh" }));
        infoRefresh.add(cmbDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 180, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("VACCINE TYPE (Dose no.)");
        infoRefresh.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        cmbDose.setBackground(new java.awt.Color(47, 79, 79));
        cmbDose.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        cmbDose.setForeground(new java.awt.Color(255, 255, 255));
        cmbDose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Dose", "Second Dose", "Booster Shot" }));
        cmbDose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDoseActionPerformed(evt);
            }
        });
        infoRefresh.add(cmbDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 180, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("VACCINE BRAND");
        infoRefresh.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        cmbBrand.setBackground(new java.awt.Color(47, 79, 79));
        cmbBrand.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        cmbBrand.setForeground(new java.awt.Color(255, 255, 255));
        cmbBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Refresh" }));
        cmbBrand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbBrandMouseExited(evt);
            }
        });
        cmbBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBrandActionPerformed(evt);
            }
        });
        infoRefresh.add(cmbBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 180, -1));

        jPanel4.setBackground(new java.awt.Color(250, 250, 210));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(47, 79, 79));
        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SCHEDULING");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        infoRefresh.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 50, 440, 530));

        jLabel7.setBackground(new java.awt.Color(47, 79, 79));
        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("(Choose vaccination date and brand available below)");
        infoRefresh.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        btnConfirmSched.setText("CONFIRM");
        btnConfirmSched.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmSchedActionPerformed(evt);
            }
        });
        infoRefresh.add(btnConfirmSched, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, -1, -1));

        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
        });
        infoRefresh.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 300, 280, 20));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        infoRefresh.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 200, 170));

        infoREF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infoREFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                infoREFMouseExited(evt);
            }
        });
        infoRefresh.add(infoREF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 200, 40));

        jPanel1.setBackground(new java.awt.Color(250, 250, 210));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(visibleCampaign, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(infoRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(infoRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbDoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDoseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDoseActionPerformed

    private void cmbBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBrandActionPerformed

    private void btnConfirmSchedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmSchedActionPerformed

        PreparedStatement ps;
        ResultSet rs;

        String insertquery = "REPLACE INTO registrantvaccine SET vrID = 1, VaccDose=?, VaccBrand=?, VaccDate=?";
        try {
            ps = ConnectToDB.getConnection().prepareStatement(insertquery);

            String DOSE = cmbDose.getSelectedItem().toString();
            ps.setString(1, DOSE);

            String BRAND = cmbBrand.getSelectedItem().toString();
            ps.setString(2, BRAND);

            String DATE = cmbDate.getSelectedItem().toString();
            ps.setString(3, DATE);

            if (ps.executeUpdate()!=0) {
                JOptionPane.showMessageDialog(null, "Scdedule Recorded");

                FinalPrinting Ir = new FinalPrinting();
                Ir.setVisible(true);
                this.setVisible(false);
                ///////

                /////////

            }else{
                JOptionPane.showMessageDialog(null, "ACCOUNT CREATION FAILED");
            }

            // TODO add your handling code here:

        } catch (SQLException ex) {
            Logger.getLogger(RegisterPage.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your h

        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmSchedActionPerformed

    private void infoRefreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoRefreshMouseEntered
       
    }//GEN-LAST:event_infoRefreshMouseEntered

    private void infoREFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoREFMouseEntered
        

    }//GEN-LAST:event_infoREFMouseEntered

    private void cmbBrandMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbBrandMouseExited
     
     
    }//GEN-LAST:event_cmbBrandMouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseEntered

    
     ImageIcon SINOVAC_IMG = new ImageIcon("SINOVAC_Campaign.png");
     ImageIcon ASTRAZENICA_IMG = new ImageIcon("ASTRAZENICA_Campaign.png");
     ImageIcon PFIZER_IMG = new ImageIcon("PFIZER_Campaign.png");
     ImageIcon MODERNA_IMG = new ImageIcon("MODERNA_Campaign.png");
     ImageIcon JOHNSON_IMG = new ImageIcon("JOHNSON_Campaign.png");
     ImageIcon GAMALEYA_IMG = new ImageIcon("GAMALEYA_Campaign.png");
     ImageIcon SINOPHARM_IMG = new ImageIcon("SINOPHARM_Campaign.png");
    
    
    
    
    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        
    }//GEN-LAST:event_jLabel6MouseEntered

    private void infoREFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoREFMouseExited
        cmbBrand.removeAllItems();
        cmbDate.removeAllItems();
        PreparedStatement st;
        ResultSet rs;

        String query = "SELECT * from updatevaccine WHERE vaccNum=1";

        try {
            st = ConnectToDB.getConnection().prepareStatement(query);
            rs = st.executeQuery();

            while(rs.next()){

                String Sinovac = rs.getString("SINOVAC");
                if ( "SINOVAC".equals(Sinovac)) {
                    cmbBrand.addItem(Sinovac);
                }

                String Astrazenica = rs.getString("ASTRAZENICA");
                if ("ASTRAZENICA".equals(Astrazenica)) {
                    cmbBrand.addItem(Astrazenica);
                }

                String Pfizer = rs.getString("PFIZER");
                if ("PFIZER".equals(Pfizer)) {
                    cmbBrand.addItem(Pfizer);
                }

                String Moderna = rs.getString("MODERNA");
                if ("MODERNA".equals(Moderna)) {
                    cmbBrand.addItem(Moderna);
                }

                String Johnson = rs.getString("JOHNSON");
                if ("JOHNSON".equals(Johnson)) {
                    cmbBrand.addItem(Johnson);
                }

                String Gamaleya = rs.getString("GAMALEYA");
                if ("GAMALEYA".equals(Gamaleya)) {
                    cmbBrand.addItem(Gamaleya);
                }

                String Sinopharm = rs.getString("SINOPHARM");
                if ("SINOPHARM".equals(Sinopharm)) {
                    cmbBrand.addItem(Sinopharm);
                }
///////
              
                
 


                
                
                
                
                
                
  //////////              
                java.sql.Timestamp t1 = rs.getTimestamp("vaccDate1");
                java.sql.Date  date  = new java.sql.Date(t1.getTime());
                java.util.Date d1 = new java.util.Date(date.getTime());
                SimpleDateFormat sd1 =new SimpleDateFormat("MM/dd/yyyy");

                cmbDate.addItem(sd1.format(d1));

                java.sql.Timestamp t2 = rs.getTimestamp("vaccDate2");
                java.sql.Date  date2  = new java.sql.Date(t2.getTime());
                java.util.Date d2 = new java.util.Date(date2.getTime());
                SimpleDateFormat sd2 =new SimpleDateFormat("MM/dd/yyyy");

                cmbDate.addItem(sd2.format(d2));

                java.sql.Timestamp t3 = rs.getTimestamp("vaccDate3");
                java.sql.Date  date3  = new java.sql.Date(t3.getTime());
                java.util.Date d3 = new java.util.Date(date3.getTime());
                SimpleDateFormat sd3 =new SimpleDateFormat("MM/dd/yyyy");

                cmbDate.addItem(sd3.format(d3));

                java.sql.Timestamp t4 = rs.getTimestamp("vaccDate4");
                java.sql.Date  date4  = new java.sql.Date(t4.getTime());
                java.util.Date d4 = new java.util.Date(date4.getTime());
                SimpleDateFormat sd4 =new SimpleDateFormat("MM/dd/yyyy");

                cmbDate.addItem(sd4.format(d4));

                java.sql.Timestamp t5 = rs.getTimestamp("vaccDate5");
                java.sql.Date  date5  = new java.sql.Date(t5.getTime());
                java.util.Date d5 = new java.util.Date(date5.getTime());
                SimpleDateFormat sd5 =new SimpleDateFormat("MM/dd/yyyy");

                cmbDate.addItem(sd5.format(d5));

              
            }
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_infoREFMouseExited

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
       String S = "SINOVAC";
        String A = "ASTRAZENICA";
        String P = "PFIZER";
        String M = "MODERNA";
        String J = "JOHNSON";
        String G = "GAMALEYA";
        String SI = "SINOPHARM";
       
        
 
 
        if (cmbBrand.getSelectedItem().toString().equals(S)) {
                      visibleCampaign.setIcon(SINOVAC_IMG);
                }
        
         if (cmbBrand.getSelectedItem().toString().equals(A)) {
                     visibleCampaign.setIcon(ASTRAZENICA_IMG);                
                }
         
          if (cmbBrand.getSelectedItem().toString().equals(P)) {
                    visibleCampaign.setIcon(PFIZER_IMG);                  
                }
          
           if (cmbBrand.getSelectedItem().toString().equals(M)) {
                    visibleCampaign.setIcon(MODERNA_IMG);                  
                }
           
            if (cmbBrand.getSelectedItem().toString().equals(J)) {
                    visibleCampaign.setIcon(JOHNSON_IMG);                  
                }
            
             if (cmbBrand.getSelectedItem().toString().equals(G)) {
                     visibleCampaign.setIcon(GAMALEYA_IMG);                  
                }
             
              if (cmbBrand.getSelectedItem().toString().equals(SI)) {
                   visibleCampaign.setIcon(SINOPHARM_IMG);                  
                }
    }//GEN-LAST:event_jLabel6MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntoReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntoReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntoReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntoReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntoReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmSched;
    private javax.swing.JComboBox<String> cmbBrand;
    private javax.swing.JComboBox<String> cmbDate;
    private javax.swing.JComboBox<String> cmbDose;
    private javax.swing.JLabel infoREF;
    private javax.swing.JPanel infoRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel visibleCampaign;
    // End of variables declaration//GEN-END:variables
}
