
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Main
 */
public class NewAdminAcc extends javax.swing.JFrame {

    /**
     * Creates new form NewAdminAcc
     */
    public NewAdminAcc() {
        initComponents();
           Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }

    
     public boolean verifyFields(){
        String name = adminUsername.getText();    
        String pword = String.valueOf(adminPassword.getPassword());
        String confirm = String.valueOf(adminConpassword.getPassword());
        
        if(
           name.trim().equals("") || pword.trim().equals("") || confirm.trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "All Fields are required");
            return false;
        }
        return true;
    }
    
    
      public boolean checkUsername(){
        PreparedStatement st;
        ResultSet rs;
        boolean username_exist = false;
        
        String query = "SELECT * from adminlogin WHERE AdminUserName = ?";
        try {
            st = ConnectToDB.getConnection().prepareStatement(query);
            st.setString(1, adminUsername.getText());
            rs = st.executeQuery();
            
            if(rs.next()){
                username_exist = true;
                JOptionPane.showMessageDialog(null, "Username already exists!", "Username Failed", 2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(NewAdminAcc.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        return username_exist;
    }
    
    
      
      
      
      
      
      
      
      
      
    
      
      
      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adminUsername = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        adminPassword = new javax.swing.JPasswordField();
        adminConpassword = new javax.swing.JPasswordField();
        AdminloggedIN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(47, 79, 79));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CREATE ADMIN ACCOUNT");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iMAGES/icons8-user-50.png"))); // NOI18N

        adminUsername.setBackground(new java.awt.Color(47, 79, 79));
        adminUsername.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        adminUsername.setForeground(new java.awt.Color(255, 255, 255));
        adminUsername.setText("Username");
        adminUsername.setBorder(null);
        adminUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminUsernameMouseClicked(evt);
            }
        });
        adminUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminUsernameActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));

        adminPassword.setBackground(new java.awt.Color(47, 79, 79));
        adminPassword.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        adminPassword.setForeground(new java.awt.Color(255, 255, 255));
        adminPassword.setText("password");
        adminPassword.setBorder(null);
        adminPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminPasswordMouseClicked(evt);
            }
        });
        adminPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPasswordActionPerformed(evt);
            }
        });

        adminConpassword.setBackground(new java.awt.Color(47, 79, 79));
        adminConpassword.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        adminConpassword.setForeground(new java.awt.Color(255, 255, 255));
        adminConpassword.setText("password");
        adminConpassword.setBorder(null);
        adminConpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminConpasswordMouseClicked(evt);
            }
        });
        adminConpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminConpasswordActionPerformed(evt);
            }
        });

        AdminloggedIN.setBackground(new java.awt.Color(47, 79, 79));
        AdminloggedIN.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        AdminloggedIN.setForeground(new java.awt.Color(255, 255, 255));
        AdminloggedIN.setText("SUBMIT");
        AdminloggedIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminloggedINActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(173, 173, 173))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(adminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1)
                                .addComponent(jSeparator2)
                                .addComponent(jSeparator3)
                                .addComponent(adminUsername))
                            .addComponent(adminConpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(AdminloggedIN, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(80, 80, 80)
                .addComponent(adminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(adminConpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(AdminloggedIN)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminloggedINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminloggedINActionPerformed
     
        
        PreparedStatement ps;
         ResultSet rs; 
         
         if (verifyFields()) {
             if (!checkUsername()) {
                String insertquery = "INSERT INTO adminlogin ( `AdminUserName`, `AdminPass`, `AdminConpass`)  values (?, ?, ?)";
        try {
            ps = ConnectToDB.getConnection().prepareStatement(insertquery);
            ps.setString(1, adminUsername.getText());
            ps.setString(2, String.valueOf(adminPassword.getPassword()));
            ps.setString(3,  String.valueOf(adminConpassword.getPassword()));
            
            if (ps.executeUpdate()!=0) {
                JOptionPane.showMessageDialog(null, "ACCOUNT CREATED SUCCESSFULLY");
                
                
                StudentLog Ir = new StudentLog();
                Ir.setVisible(true);
                this.setVisible(false);
                
                
                
            }else{
                JOptionPane.showMessageDialog(null, "ACCOUNT CREATION FAILED");
            }
            
// TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(RegisterPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        }                              
    }           // TODO add your handling code here:
                                              
    // TODO add your handling code here:
    }//GEN-LAST:event_AdminloggedINActionPerformed

    private void adminUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminUsernameActionPerformed
               

        // TODO add your handling code here:
    }//GEN-LAST:event_adminUsernameActionPerformed

    private void adminPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPasswordActionPerformed

  // TODO add your handling code here:
    }//GEN-LAST:event_adminPasswordActionPerformed

    private void adminConpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminConpasswordActionPerformed
       
// TODO add your handling code here:
    }//GEN-LAST:event_adminConpasswordActionPerformed

    private void adminUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminUsernameMouseClicked
 adminUsername.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_adminUsernameMouseClicked

    private void adminPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminPasswordMouseClicked
        adminPassword.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_adminPasswordMouseClicked

    private void adminConpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminConpasswordMouseClicked
             adminConpassword.setText("");


        // TODO add your handling code here:
    }//GEN-LAST:event_adminConpasswordMouseClicked

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAdminAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAdminAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAdminAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAdminAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewAdminAcc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminloggedIN;
    private javax.swing.JPasswordField adminConpassword;
    private javax.swing.JPasswordField adminPassword;
    private javax.swing.JTextField adminUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
